version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Luna115115
      MYSQL_DATABASE: escolar
      MYSQL_USER: sebas
      MYSQL_PASSWORD: Luna115115
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --bind-address 0.0.0.0
    networks:
      - mysql_network

volumes:
  mysql_data:
    driver: local

networks:
  mysql_network:
    driver: bridge